// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	accounts "github.com/d-ashesss/mah-moneh/internal/accounts"
	categories "github.com/d-ashesss/mah-moneh/internal/categories"

	mock "github.com/stretchr/testify/mock"

	transactions "github.com/d-ashesss/mah-moneh/internal/transactions"
)

// Spendings is an autogenerated mock type for the Spendings type
type Spendings struct {
	mock.Mock
}

// AddAmount provides a mock function with given fields: cat, currency, amount
func (_m *Spendings) AddAmount(cat *categories.Category, currency accounts.Currency, amount float64) {
	_m.Called(cat, currency, amount)
}

// AddAmounts provides a mock function with given fields: cat, amounts
func (_m *Spendings) AddAmounts(cat *categories.Category, amounts accounts.CurrencyAmounts) {
	_m.Called(cat, amounts)
}

// AddTransaction provides a mock function with given fields: tx
func (_m *Spendings) AddTransaction(tx *transactions.Transaction) {
	_m.Called(tx)
}

// GetAmount provides a mock function with given fields: cat, currency
func (_m *Spendings) GetAmount(cat *categories.Category, currency accounts.Currency) float64 {
	ret := _m.Called(cat, currency)

	var r0 float64
	if rf, ok := ret.Get(0).(func(*categories.Category, accounts.Currency) float64); ok {
		r0 = rf(cat, currency)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// GetAmounts provides a mock function with given fields: cat
func (_m *Spendings) GetAmounts(cat *categories.Category) accounts.CurrencyAmounts {
	ret := _m.Called(cat)

	var r0 accounts.CurrencyAmounts
	if rf, ok := ret.Get(0).(func(*categories.Category) accounts.CurrencyAmounts); ok {
		r0 = rf(cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.CurrencyAmounts)
		}
	}

	return r0
}

// GetTotal provides a mock function with given fields:
func (_m *Spendings) GetTotal() accounts.CurrencyAmounts {
	ret := _m.Called()

	var r0 accounts.CurrencyAmounts
	if rf, ok := ret.Get(0).(func() accounts.CurrencyAmounts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.CurrencyAmounts)
		}
	}

	return r0
}

// GetUnaccounted provides a mock function with given fields:
func (_m *Spendings) GetUnaccounted() accounts.CurrencyAmounts {
	ret := _m.Called()

	var r0 accounts.CurrencyAmounts
	if rf, ok := ret.Get(0).(func() accounts.CurrencyAmounts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.CurrencyAmounts)
		}
	}

	return r0
}

// GetUncategorized provides a mock function with given fields:
func (_m *Spendings) GetUncategorized() accounts.CurrencyAmounts {
	ret := _m.Called()

	var r0 accounts.CurrencyAmounts
	if rf, ok := ret.Get(0).(func() accounts.CurrencyAmounts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.CurrencyAmounts)
		}
	}

	return r0
}

type mockConstructorTestingTNewSpendings interface {
	mock.TestingT
	Cleanup(func())
}

// NewSpendings creates a new instance of Spendings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSpendings(t mockConstructorTestingTNewSpendings) *Spendings {
	mock := &Spendings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
