// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CurrencyService is an autogenerated mock type for the CurrencyService type
type CurrencyService struct {
	mock.Mock
}

// GetRate provides a mock function with given fields: from, target, month
func (_m *CurrencyService) GetRate(from string, target string, month string) float64 {
	ret := _m.Called(from, target, month)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, string, string) float64); ok {
		r0 = rf(from, target, month)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

type mockConstructorTestingTNewCurrencyService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencyService creates a new instance of CurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencyService(t mockConstructorTestingTNewCurrencyService) *CurrencyService {
	mock := &CurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
