// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	accounts "github.com/d-ashesss/mah-moneh/internal/accounts"

	context "context"

	mock "github.com/stretchr/testify/mock"

	users "github.com/d-ashesss/mah-moneh/internal/users"
)

// AccountsService is an autogenerated mock type for the AccountsService type
type AccountsService struct {
	mock.Mock
}

// GetAccountAmounts provides a mock function with given fields: ctx, acc, month
func (_m *AccountsService) GetAccountAmounts(ctx context.Context, acc *accounts.Account, month string) (accounts.CurrencyAmounts, error) {
	ret := _m.Called(ctx, acc, month)

	var r0 accounts.CurrencyAmounts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *accounts.Account, string) (accounts.CurrencyAmounts, error)); ok {
		return rf(ctx, acc, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *accounts.Account, string) accounts.CurrencyAmounts); ok {
		r0 = rf(ctx, acc, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.CurrencyAmounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *accounts.Account, string) error); ok {
		r1 = rf(ctx, acc, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAccounts provides a mock function with given fields: ctx, u
func (_m *AccountsService) GetUserAccounts(ctx context.Context, u *users.User) (accounts.AccountCollection, error) {
	ret := _m.Called(ctx, u)

	var r0 accounts.AccountCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) (accounts.AccountCollection, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) accounts.AccountCollection); ok {
		r0 = rf(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.AccountCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *users.User) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountsService creates a new instance of AccountsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountsService(t mockConstructorTestingTNewAccountsService) *AccountsService {
	mock := &AccountsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
