// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	accounts "github.com/d-ashesss/mah-moneh/internal/accounts"

	context "context"

	mock "github.com/stretchr/testify/mock"

	users "github.com/d-ashesss/mah-moneh/internal/users"
)

// AccountsService is an autogenerated mock type for the AccountsService type
type AccountsService struct {
	mock.Mock
}

// GetAccountCurrentAmounts provides a mock function with given fields: ctx, acc
func (_m *AccountsService) GetAccountCurrentAmounts(ctx context.Context, acc *accounts.Account) (accounts.AmountCollection, error) {
	ret := _m.Called(ctx, acc)

	var r0 accounts.AmountCollection
	if rf, ok := ret.Get(0).(func(context.Context, *accounts.Account) accounts.AmountCollection); ok {
		r0 = rf(ctx, acc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.AmountCollection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *accounts.Account) error); ok {
		r1 = rf(ctx, acc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAccounts provides a mock function with given fields: ctx, u
func (_m *AccountsService) GetUserAccounts(ctx context.Context, u *users.User) (accounts.AccountCollection, error) {
	ret := _m.Called(ctx, u)

	var r0 accounts.AccountCollection
	if rf, ok := ret.Get(0).(func(context.Context, *users.User) accounts.AccountCollection); ok {
		r0 = rf(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.AccountCollection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *users.User) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountsService creates a new instance of AccountsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountsService(t mockConstructorTestingTNewAccountsService) *AccountsService {
	mock := &AccountsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
